### ISSUE TITLE
Auto-reply is breaking some links

### ISSUE THREAD

**Issue by tjbh** [tjbh/lice#2]
<z2e> i found something interesting:
<z2e> if you have a string in your /ar,  and someone posts a link which includes that ar
<z2e> it changes the link to whatever case (lowercase/uppercase) you have the string in your ar
<z2e> thus rendering the link invalid
<z2e> (if it happens to differ)

Reported by z2e

**Comment by tjharman** [comment]
This was fixed in 5.2.7
