### ISSUE TITLE
sc -f fails when ctog q is enabled.

### ISSUE THREAD

**Issue by tjharman** [tjbh/lice#5]
You can't force a refreshed list of names if you've got CTOG Q set.
The ignore must cause the command to fail.

**Comment by tjbh** [comment]
I probably broke this.

**Comment by tjbh** [comment]
Its the NOTICES portion of the ignore that's blocking /SC -F

**Comment by tjbh** [comment]
https://github.com/tjbh/lice/commit/ebf9ced8d3cc96b34fef331cd6e57f8630933b13

There's the commit I broke it in.

**Comment by tjharman** [comment]
It's fine though - I'll just modify /SC so that when it takes the -F path, it checks to see if /CTOG Q is enabled and if so, removes the ignore that causes it to be be blocked, runs the NAMES command, then re-adds the IGNORE.

**Comment by tjbh** [comment]
Sounds like voodoo to me.

**Comment by tjbh** [comment]
Ignoring NOTICES doesn't block /NAMES on a clean EPIC.

**Comment by tjbh** [comment]
ON ^353 * {
  IF (iscset(Q $hash_32bit($2))) {RETURN};

From lice.irc

**Comment by tjbh** [comment]
Fixed.
